---
- name: Add PostgreSQL apt repository
  command: "sudo add-apt-repository 'deb https://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'"

- name: Import public key
  shell: "wget --quiet -O - https://postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"

- name: Update Package Lists
  apt: update_cache=yes

- name: Install Packages
  apt: name={{ item }} state=present
  with_items:
  - postgresql-{{ postgres_version }}
  - python-psycopg2
  - libpq-dev